version: 2

sources:
  - name: restaurants_sources
    schema: source
    tables:
      - name: orders
        columns:
          - name: identifier
            description: Primary key for restaurants
            tests:
              - unique
              - not_null
      - name: dishes
        columns:
          - name: identifier
            description: Primary key for restaurants
            tests:
              - unique
              - not_null